# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.1  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        exclude: 'tests|benchmarks|examples|scripts'
        #exclude: 'heat/core/tests/|heat/core/linalg/tests/|heat/cluster/tests/|heat/classification/tests/|heat/graph/tests/|heat/naive_bayes/tests/|heat/regression/tests/|heat/spatial/tests/|heat/utils/tests'
