language: python
python:
  - "3.5"
cache: pip
before_install:
  - sudo apt-get install -y libmpich-dev
  - travis_wait 32 ./install-torch.sh
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - mpirun python -m heat.core.tests.test_tensor
  - mpirun python -m heat.ml.cluster.tests.test_kmeans
