language: python
python:
- '3.7'
services:
- docker
before_install:
- pip install codecov
- docker pull markusgoetz/heat
- docker run -dt --name unittest -v $PWD:/heat markusgoetz/heat
- pip install pre-commit
install:
- pre-commit run --all-files
- docker exec -t unittest /bin/bash -c '. /root/.bashrc && pip install --progress-bar
  off -e .[hdf5,netcdf] && pip list'
script:
- |
  docker exec -t unittest /bin/bash -c '. /root/.bashrc && \
    for i in {1..4}; do mpirun --mca btl_vader_single_copy_mechanism none --mca btl ^openib --allow-run-as-root -np $i coverage run --source=heat --parallel-mode -m pytest heat/ || exit; done && \
    mpirun --mca btl_vader_single_copy_mechanism none --mca btl ^openib --allow-run-as-root -np 7 coverage run --source=heat --parallel-mode -m pytest heat/ && \
    coverage combine && \
    coverage report && \
    coverage xml'
after_success:
- codecov
deploy:
  provider: pypi
  user: heat-travis-token
  password:
    secure: Bz4pi9S3lhjj58euqi1GkFsONrjvkz/De3fG67nHSNtHESMQxnH8vs/jaN9sduA99Gdy8JHCdQgplYbBTXPE/ait3YvnVAGwMd6DcgwfkBOtLTg26w3BCr6E49OfQo9DFmLQCrRw1EyKWyGAdNSXc/u8v5ssBhVUaabscJRT/cgcQIQW5msA4+YWPdJgcyJK9S0EzQqSjyLlMb97F9q1GTVGnRSwdM3juecxifL7roCfmhXsk3+SodG67kTHQLsHysAHcckUboD6ErwP/PuvX/cPPXKUD89l6NKVCVaLub0WcV2vqiPcADB5W5hDNI47uvjDR3EH2p6+eesDqFEWrq7v2W88Iv199AhZNJBd9bHL+aIGYYVoKd7VEmWdHPd2+CMv3LLZuznw7Y0HZy0ldarp9/z5FCTuf3TPTSW1oKlWRmHui542oCqzzI1GwWmXifWdxBUAKRXpJvheVPzKYYDxRs+GnfmpD7a+4Wr1JvKW0FtPERTY68qRD7E5hPCWbfn8vxFSaZIoQP3ojpzZTPDkeJWZb7we9DeJelWcXN1DJDfeeH6wkjFbgOhi0e3z8Hu44/Aq9M24jWSwto6LTQEkoAgnyAikoi0P461odD/KFPq3gnSp0AhZSXpNt4bsb8bRNjmyW1xC3aFZ/TPSVb04AuAKsiN5n61Wn4pLvec=
  on:
    tags: true
  skip_cleanup: true
