name: Support latest PyTorch

on:
  push:
    paths:
      - '.github/workflows/pytorch-release-versions/*'
permissions:
  contents: read
  issues: write
jobs:
  latest-torch-support:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id:
          create-issue
        with:
          filename: .github/ISSUE_TEMPLATE/support_latest_pytorch.md
          milestone: 1
          update_existing: true
          search_existing: open
      - run: echo "creating new issue"
      - uses: actions/checkout@v2
        with:
          ref: 'features/latest-pytorch-support'
      - run: echo "checking out new branch"
      - uses: peter-evans/create-pull-request@v3
        with:
            ref: 'features/latest-pytorch-support'
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Support latest PyTorch release
            title: Support latest PyTorch release
            body: |
              Run tests on latest PyTorch release
              Issue/s resolved: #${{ steps.create-issue.outputs.number }}
              Auto-generated by [create-pull-request][1]
              [1]: https://github.com/peter-evans/create-pull-request
              branch: features/latest-pytorch-support
      - run: echo "creating PR"
