name: Support latest PyTorch

on:
  push:
    paths:
      - '.github/workflows/pytorch-release-versions/*'
env:
  previous_pytorch: $(grep 'torch>=' setup.py | awk -F '<=' '{print $2}' | tr -d '",')
  new_pytorch: $(<.github/workflows/pytorch-release-versions/pytorch-latest.txt)
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  latest-torch-support:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id:
          create-issue
        with:
          filename: .github/ISSUE_TEMPLATE/support_latest_pytorch.md
          milestone: 1
          update_existing: true
          search_existing: open
      - run: echo "New issue created"
      - name: Check out new branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'features/latest-pytorch-support'
      - name: Update setup.py
        run: |
          echo ${{ env.previous_pytorch }}
          echo ${{ env.new_pytorch }}
          sed -i '/torch>=/ s/'"${{ env.previous_pytorch }}"'/'"${{ env.new_pytorch }}"'/g' setup.py
          sed -i 's/'"${{ env.previous_pytorch }}"'/'"${{ env.new_pytorch }}"'/g' .github/workflows/pytorch-release-versions/pytorch-latest.txt
      - name: Create PR from branch
        uses: peter-evans/create-pull-request@v3
        with:
            base: features/latest-pytorch-support
            delete-branch: true
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Support latest PyTorch release
            title: Support PyTorch ${{ env.new_pytorch }}
            body: |
              Run tests on latest PyTorch release
              Issue/s resolved: #${{ steps.create-issue.outputs.number }}
              Auto-generated by [create-pull-request][1]
              [1]: https://github.com/peter-evans/create-pull-request
