name: Support latest PyTorch

on:
  push:
    paths:
      - '.github/workflows/pytorch-release-versions/*'
permissions:
  contents: read
  issues: write
jobs:
  latest-torch-support:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id:
          create-issue
        with:
          filename: .github/ISSUE_TEMPLATE/support_latest_pytorch.md
          milestone: 1
          update_existing: true
          search_existing: open
      - run: echo "creating new issue"
      - name: Check out branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'features/latest-pytorch-support'
      - name: Update torch version in setup.py
        id: update-setup-py
        run: |
          previous_pytorch=$(grep 'torch>=' setup.py | awk -F '<=' '{print $2}' | tr -d '",')
          new_pytorch=$(<.github/workflows/pytorch-release-versions/pytorch-latest.txt)
          sed -i '/torch>=/ s/'"${previous_pytorch}"'/'"${new_pytorch}"'/g' setup.py
          git config --global user.name 'ClaudiaComito'
          git config --global user.email 'c.comito@fz-juelich.de@users.noreply.github.com'
          git commit -am "Update setup.py with latest pytorch release"
          git push
          echo ::set-output name=new_pytorch::$(echo $new_pytorch)
      - name: Create PR from branch
        uses: peter-evans/create-pull-request@v3
        with:
            branch: features/latest-pytorch-support
            base: master
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Support latest PyTorch release
            title: Support PyTorch ${{ steps.update-setup-py.outputs.new_pytorch }}
            body: |
              Run tests on latest PyTorch release
              Issue/s resolved: #${{ steps.create-issue.outputs.number }}
              Auto-generated by [create-pull-request][1]
              [1]: https://github.com/peter-evans/create-pull-request
