name: Support latest PyTorch

on:
  schedule:
    - cron:  '18 10 * * 2'
env:
  previous_pytorch: $(grep 'torch>=' setup.py | awk -F '<=' '{print $2}' | tr -d '",')
  new_pytorch: $(curl -sL https://api.github.com/repos/pytorch/pytorch/releases/latest | jq -r ".tag_name" | tr -d 'v')
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  latest-torch-support:
    if: env.new_pytorch != env.previous_pytorch
    strategy:
      matrix:
        branches: ['main', 'release/1.2.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id:
          create-issue
        with:
          filename: .github/ISSUE_TEMPLATE/support_latest_pytorch.md
          milestone: 1
          update_existing: true
          search_existing: open
      - name: Check out new branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ matrix.branches }}
      - name: Update setup.py
        run: |
          echo ${{ env.previous_pytorch }}
          echo ${{ env.new_pytorch }}
          sed -i '/torch>=/ s/'"${{ env.previous_pytorch }}"'/'"${{ env.new_pytorch }}"'/g' setup.py
          sed -i 's/'"${{ env.previous_pytorch }}"'/'"${{ env.new_pytorch }}"'/g' .github/pytorch-release-versions/pytorch-latest.txt
      - name: Define env variable
        run: |
          echo "new=$(<.github/pytorch-release-versions/pytorch-latest.txt)" >> $GITHUB_ENV
      - name: Create PR from branch
        uses: peter-evans/create-pull-request@v3
        with:
            base: ${{ matrix.branches }}
            delete-branch: true
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Support latest PyTorch release
            title: Support PyTorch ${{ env.new }} on branch ${{ matrix.branches }}
            body: |
              Run tests on latest PyTorch release
              Issue/s resolved: #${{ steps.create-issue.outputs.number }}
              Auto-generated by [create-pull-request][1]
              [1]: https://github.com/peter-evans/create-pull-request
            reviewers: ClaudiaComito, mtar, coquelin77, JuanPedroGHM
