on:
  push:
    paths:
      - 'python-release-versions/*'
name: Support latest PyTorch
permissions:
  contents: read
  issues: write
jobs:
  latest-torch-support:
    runs-on: ubuntu-latest
    steps:
      - name: create issue
        uses: actions/checkout@v2
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id:
          create-issue
        with:
          filename: .github/ISSUE_TEMPLATE/support_latest_pytorch.md
          milestone: 1
          update_existing: true
          search_existing: open
      - name: Check out branch
        uses: actions/checkout@v2
        with:
          ref: 'features/latest-pytorch-support'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Support latest PyTorch release
            title: Support latest PyTorch release
            body: |
              Run tests on latest PyTorch release
              Issue/s resolved: #${{ steps.create-issue.outputs.number }}
              Auto-generated by [create-pull-request][1]
              [1]: https://github.com/peter-evans/create-pull-request
              branch: features/latest-pytorch-support
