name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    container:
      image: docker://markusgoetz/heat
      volumes:
        - heat/
        - /lib/modules
        - /usr/src
      options:
        - --privileged
        - --cap-add=ALL
    steps:
      - uses: actions/checkout@v1
      - name: Shell check
        run: |
          echo $SHELL
          cat /etc/os-release
      - name: Installing
        run: |
          dnf -y update
          dnf -y install @development-tools redhat-rpm-config python3-devel openmpi-devel hdf5-openmpi-devel netcdf-openmpi-devel
          echo $SHELL
          module avail
          module list
          module load mpi
          mpirun --version
      - name: Install dependecies
        run: |
          sudo /bin/bash -c '. /root/.bashrc && pip install -q -e .[hdf5,netcdf]'
          sudo /bin/bash -c '. /root/.bashrc && pip list'
      - name: Test with pytest
        run: |
          sudo /bin/bash -c '. /root/.bashrc && pytest'
