name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        uses: docker://markusgoetz/heat
      - uses: actions/checkout@v1
      - name: Install dependecies
        shell: bash
        run: |
          pip install -q -e .[hdf5,netcdf]
          pip list
      - name: Test with pytest
        shell: bash
        run: |
          pip install pytest
          pytest
