name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  run-tests:
    name: Run Unittests
    runs-on: ubuntu-latest
    container: docker://simonsdockerid/heat
    steps:
      - uses: actions/checkout@v1
      - name: check shell
        run: echo $SHELL
      - name: Install Python Dependencies
        run: pip install -q -e .[hdf5,netcdf]
      - name: Run Python Tests
        run: |
          for i in {1..4}; do
            mpirun --mca btl_vader_single_copy_mechanism none --mca btl ^openib --allow-run-as-root -np $i coverage run --source=heat --parallel-mode -m pytest heat/ || exit;
          done
          mpirun --mca btl_vader_single_copy_mechanism none --mca btl ^openib --allow-run-as-root -np $i coverage run --source=heat --parallel-mode -m pytest heat/
      - name: Combine Coverage Report
        run: |
          coverage combine
          coverage report
          coverage xml
# TODO add codecov  action https://github.com/marketplace/actions/codecov
