name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    container: docker://simonsdockerid/heat
    steps:
      - name: Check MPI
        run: mpirun --version
      - name: Activate virtualenv
        run: |
          echo $HOME
          whoami
          . /root/.virtualenvs/heat/bin/activate
          pip -V
      - name: Check venv
        run: pip -V
