name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker Image
        uses: docker://markusgoetz/heat
      - uses: actions/checkout@v1
      - name: Debugging info
        run: |
          ls
          /bin/bash -c '. /root/.bashrc && mpirun --version'
      - name: Install dependecies
        run: |
          /bin/bash -c '. /root/.bashrc && pip install -q -e .[hdf5,netcdf]'
          /bin/bash -c '. /root/.bashrc && pip list'
      - name: Test with pytest
        run: |
          /bin/bash -c '. /root/.bashrc && pip install pytest'
          /bin/bash -c '. /root/.bashrc && pytest'
