name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: docker://simondockerid/heat:latest
      - run: |
          echo $BASH_ENV
          mpirun --version
