name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    container:
      image: docker://simonsdockerid/heat
    steps:
      - uses: actions/checkout@v1
      - name: Shell check
        run: module list
      - name: Installing
        run: mpirun --version
      - name: Check dir
        run: ls
#      - name: Install dependecies
#        run: pip install -q -e .[hdf5,netcdf]
#      - name: Test with pytest
#        run: pytest
