name: Get latest PyTorch release version
on:
  schedule:
    - cron:  '55 11 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: workflow/pytorch-new-release
      - name: Fetch PyTorch release version
        run: |
          curl -sL https://api.github.com/repos/pytorch/pytorch/releases/latest | \
          jq -r ".tag_name" > .github/workflows/python-release-versions/pytorch-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest PyTorch release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'ClaudiaComito'
          git config --global user.email 'c.comito@fz-juelich.de@users.noreply.github.com'
          git commit -am "New PyTorch release"
          git push
