name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    container:
      image: docker://orwel84/ubuntu-16-mpi
      volumes:
        - $PWD:/heat
    steps:
      - uses: actions/checkout@v1
      - name: Shell check
        run: |
          echo $SHELL
          cat /etc/os-release
      - name: Installing
        run: |
          mpirun --version
          mpirun -np 4 --allow-run-as-root ./mpi_hello_world
